### ISSUE TITLE
minor adjusment on section 7, 8 & 9

### ISSUE THREAD

**Issue by hitzvera** [Team4FullstackDev/html_css-e_commerce#15]
## 1. pada setiap title section bisa diberi margin sedikit.
![image](https://github.com/Team4FullstackDev/html_css-e_commerce/assets/84704847/ad317a11-c44d-4611-a3ac-91c355caf76f)

## 2. jika mereferensi pada website kyou.id pada setiap card di setiap section tidak perlu diberikan background abu abu. 
![image](https://github.com/Team4FullstackDev/html_css-e_commerce/assets/84704847/25541373-180b-4cba-be81-b3826a41c6b0)

## 3. Untuk copy writing bisa ditambah DP harga (sesuai dengan website kyou.id). dan juga judul tiap card dikasih font weigh bold agar sesuai 
![image](https://github.com/Team4FullstackDev/html_css-e_commerce/assets/84704847/c8fc49d0-cba8-45e9-b471-3ef7258465b8)

cc @nevgard

**Comment by nevgard** [comment]
okee aku revisi bang, thankuu
